openapi: 3.0.1
info:
  title: Cooking ToDo Back End Documentation
  description: >-
    todo
  license:
    name: MIT
  version: "0.0.1"
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Recettes
    description: a recipe
paths:
  /recettes:
    post:
      tags:
        - Recette
      summary: Return a hello world
      operationId: createRecette
      responses:
        '200':
          description: Successful operation. Return hello world
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorld'
components:
  schemas:
    HelloWorld:
      type: object
      properties:
        message: 
          type: string
          description: the return message
          default: "hello world"